# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "BEER" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"country" VARCHAR NOT NULL,"style" INTEGER NOT NULL,"strength" DOUBLE NOT NULL);

# --- !Downs

drop table "BEER";

