# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "beer" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"country" VARCHAR NOT NULL,"style" INTEGER NOT NULL,"tasty" BOOLEAN NOT NULL,"strength" DOUBLE NOT NULL,"comment" VARCHAR NOT NULL,"created_at" TIMESTAMP NOT NULL,"updated_at" TIMESTAMP NOT NULL);
create table "beer2" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"country" VARCHAR NOT NULL,"style" INTEGER NOT NULL,"tasty" BOOLEAN NOT NULL,"strength" DOUBLE NOT NULL,"comment" VARCHAR NOT NULL,"created_at" TIMESTAMP NOT NULL,"updated_at" TIMESTAMP NOT NULL);

# --- !Downs

drop table "beer";
drop table "beer2";

